name: testing

on:
  push:
    branches: [ none ]
  pull_request:
    branches: [ none ]

  workflow_dispatch:
    branches: [ main, post_testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
