name: post testing
on: 
  workflow_run:
    workflows: ["testing"]
    types:
      - completed

jobs:

  hello-there: 
    runs-on: ubuntu-latest
    steps:
    - name: hello world
      run: echo 'hello world from hello-there'
      
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow.run.conclusion == 'success' }}
    steps:
    - name: main success 
      run: echo "hello from main success"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow.run.conclusion == 'failure' }}
    steps:
    - name: main failure
      run: echo "hello from main failure"
