name: after_testing
on: 
  workflow_run:
    workflows: ["testing"]
    types:
      - completed

jobs:

  hello-there: 
    runs-on: ubuntu-latest
    steps:
    - name: hello_world
      id: extract_branch
      run: | 
          echo 'hello world from job after_testing'
          echo 'status is... ' ${{ github.event.workflow_run.conclusion }} 
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" 
          
    - name: which_branch
      run: |
        echo I am running in branch . . . 
        echo ${{ steps.extract_branch.outputs.branch }}

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: main success 
      run: echo "hello from main success"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: main failure
      run: echo "hello from main failure"
