# This is a basic workflow to help you get started with Actions

name: testing

  
# Controls when the workflow will run 
on:

# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ none ]
  pull_request:
    branches: [ none ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:


  hello-there: 
    runs-on: ubuntu-latest
    steps:
    - name: hello_world
      id: extract_branch
      run: | 
          echo 'hello world from testing.yml'
          echo 'status is... ' ${{ github.event.workflow_run.conclusion }} 
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" 
          
    - name: which_branch
      run: |
        echo I am running in branch . . . 
        echo ${{ steps.extract_branch.outputs.branch }}

  build:
    runs-on: ubuntu-latest

    steps:
      - run: | 
          echo 'hello from testing.yml'
          ${{ env.WORKFLOW_CONCLUSION }} = success
          echo ' workflow conclusion is: ' ${{ env.WORKFLOW_CONCLUSION }}
      
      
