name: testing

# note: this is not in the main branch....

on:

  push:
    branches: [ none ]
  pull_request:
    branches: [ none ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: | 
          echo 'hello from testing.yml'
          ${{ env.WORKFLOW_CONCLUSION }} = failure
          echo ' workflow conclusion is: ' ${{ env.WORKFLOW_CONCLUSION }}
      
  
